# Generated by Django 2.2.3 on 2019-07-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190720_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='dath_of_birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='dath_of_death',
            new_name='date_of_death',
        ),
    ]
